from .Gst import Element, Sample

class AppSink(Element):
    def pull_sample(self) -> Sample | None: ...
    def try_pull_sample(self, timeout: int) -> Sample | None: ...
    def pull_preroll(self) -> Sample | None: ...
    def try_pull_preroll(self, timeout: int) -> Sample | None: ...

